### ISSUE TITLE
[BUG] panic when rendering pdf

### ISSUE THREAD

**Issue by silentbat** [Trivernis/snekdown#21]
**Describe the bug**
when trying to render a pdf, snekdown cannot find a Chromium executable and panics:
```
PS C:\Users\User\Documents\snek> snekdown render -f pdf input.md output.pdf
info: Parsing + Processing took: 10.1979ms
info: Rendering html...
thread 'main' panicked at 'Failed to render pdf!: ChromiumError(ErrorMessage { msg: "Could not auto detect a chrome executable" })', C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\snekdown-0.33.3\src/main.rs:238:42
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**To Reproduce**
1. `cargo install snekdown --features pdf`
2. `snekdown init`
3. create some *.md and add style.css
4. `snekdown render -f pdf input.md output.pdf`

**Expected behavior**
snekdown creates a pdf

**Desktop (please complete the following information):**
 - OS: Win10
 - Architecture: x86_64
 - Version snekdown 0.33.3

**Comment by Trivernis** [comment]
Do you have google chrome or chromium installed on your system?

**Comment by silentbat** [comment]
I do have Google Chrome Canary installed, no stable version though.
Do I need to install Chrome outside of rust/snekdown/... ?

**Comment by Trivernis** [comment]
I think it should have downloaded a binary automatically when it doesn't detect a locally installed chromium. I'll look further into it

**Comment by Trivernis** [comment]
The crate I'm using for starting a headless chromium should download chromium when not installed but I don't really trust it. The version I'm getting from crates.io looks different from the one on GitHub.
